#!/usr/bin/env python3
"""Manage configuration profiles for different DHA portals and environments."""

import argparse
import os
import sys
from pathlib import Path
from typing import Dict, Optional


class ConfigManager:
    """Manage environment configurations for batch processing."""

    PROFILES_DIR = Path(".env.profiles")
    DEFAULT_ENV = Path(".env")

    def __init__(self):
        self.profiles_dir = self.PROFILES_DIR
        self.profiles_dir.mkdir(exist_ok=True)

    def create_profile(self, name: str, portal_url: str, username: str, password: str, headless: bool = False, delay_secs: float = 1.5) -> bool:
        """Create a new configuration profile."""
        profile_file = self.profiles_dir / f"{name}.env"

        content = f"""# Configuration Profile: {name}
# Generated by config_manager.py

# Portal URL
PORTAL_URL={portal_url}

# Portal login credentials
PORTAL_USER={username}
PORTAL_PASS={password}

# Browser settings
# Set to False for debugging (see browser window), True for headless mode
HEADLESS={'True' if headless else 'False'}

# Delay between claims in seconds (to avoid rate limiting)
DELAY_SECS={delay_secs}
"""

        with open(profile_file, "w") as f:
            f.write(content)

        print(f"✓ Created profile: {name}")
        print(f"  Location: {profile_file}")
        return True

    def list_profiles(self) -> None:
        """List all available profiles."""
        profiles = list(self.profiles_dir.glob("*.env"))

        if not profiles:
            print("No profiles found. Create one with: config_manager.py create <name>")
            return

        print("Available profiles:")
        for profile_file in sorted(profiles):
            name = profile_file.stem
            # Extract portal URL from file
            try:
                with open(profile_file) as f:
                    for line in f:
                        if line.startswith("PORTAL_URL="):
                            url = line.split("=", 1)[1].strip()
                            print(f"  • {name:20} → {url}")
                            break
            except Exception:
                print(f"  • {name:20} (error reading)")

    def load_profile(self, name: str, target: Path = None) -> bool:
        """Load a profile as active configuration."""
        if target is None:
            target = self.DEFAULT_ENV

        profile_file = self.profiles_dir / f"{name}.env"

        if not profile_file.exists():
            print(f"Error: Profile not found: {name}")
            print("Available profiles:")
            self.list_profiles()
            return False

        try:
            with open(profile_file) as src:
                content = src.read()

            with open(target, "w") as dst:
                dst.write(content)

            print(f"✓ Loaded profile: {name}")
            print(f"  Active config: {target}")
            return True
        except Exception as e:
            print(f"Error loading profile: {str(e)}")
            return False

    def show_current(self, env_file: Path = None) -> None:
        """Show current active configuration."""
        if env_file is None:
            env_file = self.DEFAULT_ENV

        if not env_file.exists():
            print(f"No active configuration file: {env_file}")
            return

        print(f"Active configuration: {env_file}")
        print("-" * 60)

        try:
            with open(env_file) as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith("#"):
                        continue
                    if "=" in line:
                        key, value = line.split("=", 1)
                        if key == "PORTAL_PASS":
                            value = "***" + value[-4:] if len(value) > 4 else "***"
                        print(f"  {key}: {value}")
        except Exception as e:
            print(f"Error reading config: {str(e)}")

    def delete_profile(self, name: str) -> bool:
        """Delete a profile."""
        profile_file = self.profiles_dir / f"{name}.env"

        if not profile_file.exists():
            print(f"Error: Profile not found: {name}")
            return False

        try:
            profile_file.unlink()
            print(f"✓ Deleted profile: {name}")
            return True
        except Exception as e:
            print(f"Error deleting profile: {str(e)}")
            return False


def main():
    """CLI entry point for config management."""
    parser = argparse.ArgumentParser(
        description="Manage DHA eClaim batch processing configuration profiles",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s create prod --url "https://portal.dha.gov/eclaim" --user alice --pass secret
  %(prog)s create staging --url "https://staging.dha.gov" --user bob --pass secret123
  %(prog)s load prod                     # Activate prod profile
  %(prog)s list                          # Show available profiles
  %(prog)s show                          # Show active configuration
  %(prog)s delete staging                # Remove a profile
        """,
    )

    subparsers = parser.add_subparsers(dest="command", help="Command")

    # Create command
    create_parser = subparsers.add_parser("create", help="Create a new configuration profile")
    create_parser.add_argument("name", help="Profile name (e.g., prod, staging, test)")
    create_parser.add_argument("-u", "--url", required=True, help="Portal URL")
    create_parser.add_argument("-U", "--user", required=True, help="Portal username")
    create_parser.add_argument("-p", "--pass", dest="password", required=True, help="Portal password")
    create_parser.add_argument("--headless", action="store_true", help="Enable headless mode (production)")
    create_parser.add_argument("-d", "--delay", type=float, default=1.5, help="Delay between claims (default: 1.5s)")

    # Load command
    load_parser = subparsers.add_parser("load", help="Load a profile as active configuration")
    load_parser.add_argument("name", help="Profile name to load")

    # List command
    subparsers.add_parser("list", help="List all available profiles")

    # Show command
    subparsers.add_parser("show", help="Show current active configuration")

    # Delete command
    delete_parser = subparsers.add_parser("delete", help="Delete a configuration profile")
    delete_parser.add_argument("name", help="Profile name to delete")

    args = parser.parse_args()

    manager = ConfigManager()

    if args.command == "create":
        manager.create_profile(
            name=args.name,
            portal_url=args.url,
            username=args.user,
            password=args.password,
            headless=args.headless,
            delay_secs=args.delay,
        )
    elif args.command == "load":
        success = manager.load_profile(args.name)
        return 0 if success else 1
    elif args.command == "list":
        manager.list_profiles()
    elif args.command == "show":
        manager.show_current()
    elif args.command == "delete":
        success = manager.delete_profile(args.name)
        return 0 if success else 1
    else:
        parser.print_help()
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
